name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  security-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checout the repository
      uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependecies
      run: npm install
    - name: Run integration tests
      run: npm run test-npm-security

  integration-tests:
    needs: security-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checout the repository
      uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependecies
      run: npm install
    - name: Run integration tests
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
